# autogenerated by txs
#include:iftex
#include:infwarerr
#include:ltxcmds
\csname#S
\empty#S
\expandafter#S
\pdfdraftmode#S
\x#S
\x{arg1}{arg2}#S
\x{arg1}{arg2}{arg3}#S
\y#S
\z#S
iftex.sty#S
infwarerr.sty#S
y#S
